version: '3.8'

services:
  catalog-bff-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: catalog-bff-service
    ports:
      - "8085:8085"
    environment:
      - PORT=8085
      - PIM_SERVICE_URL=http://mc-pim-service:8090
      - STOCK_SERVICE_URL=http://mc-stock-service:8080
      - TENANT_SERVICE_URL=http://mc-tenant-service:8120
      - IAM_SERVICE_URL=http://mc-iam-service:8080
    networks:
      - lab-network

networks:
  lab-network:
    external: true
