FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.7

# Copiar go mod files
COPY go.mod go.sum ./
RUN go mod download

# Copiar código fuente
COPY . .

# Exponer puerto
EXPOSE 8085

# Usar air para hot reload
CMD ["air", "-c", ".air.toml"]
